// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'sideai-pane-header'
  | 'sideai-pane-sidenav'
  | 'sideai-startup-message';
